apiVersion: v1
kind: ConfigMap
metadata:
  name: "pols-place-appsettings"
  namespace: {{ .Release.Namespace }}
  labels:
    app: pols-place
    release: {{ .Release.Name }}
data:
  appsettings.json: |
{{- if .Values.deployment.appsettings }}
  {{- .Values.deployment.appsettings | toPrettyJson | nindent 4 }} 
{{- end }}  