apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: birthdays
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: {{ .Chart.Name }}