apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pols-place
  namespace: birthdaypies
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslTermination | quote }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header x-forwarded-host "pols-place.the-farmer.io";
      proxy_set_header x-forwarded-proto "https";
      rewrite ^ $request_uri;
      rewrite ^([^?]*) $1;
    {{- if .Values.ingress.cors.enabled -}}  
    nginx.ingress.kubernetes.io/enable-cors: {{ .Values.ingress.cors.enabled | quote }}
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.ingress.cors.allowOrigin | quote }}
    nginx.ingress.kubernetes.io/cors-allow-headers: {{ include "get-allowed-cors-headers" . }}
    {{- end }}
spec:
  rules:
  - host: pols-place.the-farmer.io
    http:
      paths:
      - backend:
          service:
            name: pols-place
            port:
              number: 80
        path: (/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - pols-place.the-farmer.io
    secretName: pols-place-tls